rust:
  - '**.rs'
  - '**/Cargo.lock'
  - '**/Cargo.toml'

dependencies:
  - '**/Cargo.lock'

github_actions:
  - '.github/workflows/**'
  - '.github/labeler.yml'
  - '.github/triage-labeler.yml'

python:
  - '**/*.py'
  - '**/poetry.lock'
  - '**/pyproject.toml'
  - '**/requirements.txt'
