rust:
  - changed-files:
    - any-glob-to-any-file: 
      - '**.rs'
      - '**/Cargo.lock'
      - '**/Cargo.toml'

dependencies:
  - changed-files:
    - any-glob-to-any-file: 
      - '**/Cargo.lock'

github_actions:
  - changed-files:
    - any-glob-to-any-file: 
      - '.github/workflows/**'
      - '.github/labeler.yml'
      - '.github/triage-labeler.yml'

python:
  - changed-files:
    - any-glob-to-any-file: 
      - '**/*.py'
      - '**/poetry.lock'
      - '**/pyproject.toml'
      - '**/requirements.txt'
