[workspace]
resolver = "2"
members = [
	"panic/abort",
]

[profile.dev]
opt-level = 0
rpath = true

[profile.release]
opt-level = 3
rpath = false
lto = false
debug-assertions = false
overflow-checks = false

# Skip the need for LD_LIBRARY_PATH in `cargo test`
[profile.test]
rpath = true

