[workspace]
resolver = "2"
members = [
    "capable/sys",
    "capable/sys/types",
    "core/sys/types",
    "core/build",
    "dcap/sys/types",
    "dcap_ql/sys",
    "dcap_ql/sys/types",
    "dcap_quoteverify/sys",
    "dcap_quoteverify/sys/types",
    "dcap_tvl/sys",
    "panic/abort",
    "quote_verify",
    "tcrypto/sys",
    "tcrypto/sys/types",
    "tservice/sys",
    "tservice/sys/types",
    "trts/sys",
    "tstdc/sys",
    "tstdc/sys/types",
    "urts",
    "urts/sys",
    "urts/sys/types",
]
exclude = [
    "test_enclave",
]

[profile.dev]
opt-level = 0
lto = true

[profile.release]
opt-level = 3
rpath = false
lto = true
debug-assertions = false
overflow-checks = false
