[workspace]
resolver = "2"
members = [
    "capable/sys",
    "capable/sys/types",
    "core/sys/types",
    "core/build",
    "tcrypto/sys/types",
    "tcrypto/sys",
    "panic/abort",
    "quote_verify",
    "tservice/sys",
    "tservice/sys/types",
    "trts/sys",
    "urts",
    "urts/sys",
    "urts/sys/types",
]
exclude = [
    "test_enclave",
]

[profile.dev]
opt-level = 0
rpath = true
lto = true

[profile.release]
opt-level = 3
rpath = false
lto = true
debug-assertions = false
overflow-checks = false

# Skip the need for LD_LIBRARY_PATH in `cargo test`
[profile.test]
rpath = true
