[package]
name = "mc-sgx-service-sys-types"
version = "0.1.0"
edition = "2021"

[dependencies]
mc-sgx-core-sys-types = { path = "../../../core/sys/types" }

[build-dependencies]
bindgen = "0.60.1"
mc-sgx-core-build = { path = "../../../core/build" }
