[package]
name = "mc-sgx-urts"
version = "0.1.0"
edition = "2021"

[dependencies]
mc-sgx-urts-ffi = { path = "ffi", default-features = false }

[features]
hw = ["mc-sgx-urts-ffi/hw"]
default = []

[dev-dependencies]
test_enclave = { path = "../test_enclave" }
