[package]
name = "mc-sgx-service-ffi-types"
version = "0.1.0"
edition = "2021"

[dependencies]
mc-sgx-core-ffi-types = { path = "../../../core/ffi/types" }

[build-dependencies]
bindgen = "0.60.1"
mc-sgx-core-build = { path = "../../../core/build" }
