[package]
name = "mc-sgx-tservice"
version = "0.2.1-pre"
edition = "2021"
authors = ["MobileCoin"]
rust-version = "1.62.1"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/mobilecoinfoundation/sgx"
description = "Rust wrappers for the `sgx_tservice` library."

categories = ["api-bindings", "hardware-support"]
keywords = ["sgx"]

[dependencies]
mc-sgx-core-sys-types = { path = "../core/sys/types", version = "=0.2.1-pre" }
mc-sgx-core-types = { path = "../core/types", version = "=0.2.1-pre" }
mc-sgx-tservice-sys = { path = "sys", version = "=0.2.1-pre" }
mc-sgx-tservice-sys-types = { path = "sys/types", version = "=0.2.1-pre" }
mc-sgx-tservice-types = { path = "types", version = "=0.2.1-pre", features = [ "alloc" ] }
mc-sgx-util = { path = "../util", version = "=0.2.1-pre" }

[dev-dependencies]
mc-sgx-tservice-types = { path = "types", version = "=0.2.1-pre", features = [ "test-utils" ] }
