[package]
name = "mc-sgx-core-types"
# When updating version, update the deps.rs link in README.md
version = "0.1.0"
edition = "2021"

[dependencies]
mc-sgx-core-sys-types = { path = "../sys/types", version = "=0.1.0" }
serde = { version = "1.0.143", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
yare = "1.0.1"
