[package]
name = "mc-sgx-core-types"
version = "0.1.0"
edition = "2021"

[dependencies]
mc-sgx-core-sys-types = { path = "../sys/types", version = "=0.1.0" }
serde = { version = "1.0.144", default-features = false, features = ["derive"], optional = true }

[features]
serde = ["dep:serde"]

[dev-dependencies]
yare = "1.0.1"
