[package]
name = "mc-sgx-quote-verify"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.2"
hex = "0.4.3"
displaydoc = "0.2.3"
p256 = { version = "0.11.1", features = [ "ecdsa", "pem" ] }
x509-parser = "0.14.0"
