[package]
name = "mc-sgx-tstdc-sys"
version = "0.1.0"
edition = "2021"
rust-version = "1.62.1"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/mobilecoinfoundation/sgx"
authors = ["MobileCoin"]
description = '''
This crate contains the FFI linkage for the `libsgx_tstdc.a` library.
'''

[lib]
# test false due to needing trts, and thus an enclave to fully link
test = false

[dependencies]
mc-sgx-tstdc-sys-types = { path = "types" }
mc-sgx-core-sys-types = { path = "../../core/sys/types" }

[build-dependencies]
bindgen = "0.60.1"
cargo-emit = "0.2.1"
mc-sgx-core-build = { path = "../../core/build" }
