[package]
name = "mc-sgx-capable"
version = "0.1.0"
edition = "2021"
authors = ["MobileCoin"]
rust-version = "1.62.1"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/mobilecoinfoundation/sgx"
description = '''
This crate exposes an idiomatic rust interface to the SGX SDK's `libsgx_capable` libraries.
'''

[dependencies]
mc-sgx-capable-ffi = { path = "ffi" }
