[package]
name = "mc-sgx-capable"
# When updating version, update the deps.rs link in README.md
version = "0.1.0"
edition = "2021"
authors = ["MobileCoin"]
rust-version = "1.62.1"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/mobilecoinfoundation/sgx"
description = "Rust wrappers for the `sgx_capable` library."

categories = ["api-bindings", "hardware-support"]
description = "FFI linkage for the `sgx_capable` library."
edition = "2021"
keywords = ["sgx"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/mobilecoinfoundation/sgx"
rust-version = "1.62.1"

[dependencies]
mc-sgx-capable-sys = { path = "sys", version = "=0.1.0" }
