[package]
name = "mc-sgx-dcap-types"
version = "0.3.1-beta.0"
authors = ["MobileCoin"]
categories = ["api-bindings", "hardware-support"]
description = "Rust wrapper for common DCAP types."
edition = "2021"
keywords = ["ffi", "sgx"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/mobilecoinfoundation/sgx"
rust-version = "1.62.1"

[features]
default = []
serde = ["dep:serde"]
alloc = []

[dependencies]
displaydoc = { version = "0.2.3", default-features = false }
mc-sgx-core-types = { path = "../../core/types", version = "=0.3.1-beta.0" }
mc-sgx-dcap-sys-types = { path = "../sys/types", version = "=0.3.1-beta.0" }
mc-sgx-util = { path = "../../util", version = "=0.3.1-beta.0" }
serde = { version = "1.0.145", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
mc-sgx-core-sys-types = { path = "../../core/sys/types", version = "=0.3.1-beta.0" }
yare = "1.0.1"
