name: rust

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: [self-hosted, Linux, small]
    container: mobilecoin/rust-sgx-base:latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - uses: ./.github/actions/dcap-libs
      - run: cargo build --release --locked
  test:
    runs-on: [self-hosted, Linux, small]
    container: mobilecoin/rust-sgx-base:latest
    env:
      LD_LIBRARY_PATH: "/opt/intel/sgxsdk/lib64"
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - uses: ./.github/actions/dcap-libs
      - run: cargo test --release --locked --features sim
  doc:
    runs-on: [self-hosted, Linux, small]
    container: mobilecoin/rust-sgx-base:latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - uses: ./.github/actions/dcap-libs
      - run: cargo doc --release --locked --no-deps --features sim
