[package]
name = "mc-sgx-urts-ffi-types"
version = "0.1.0"
edition = "2021"

[features]
sw = []
default = ["sw"]

[dev-dependencies]
test_enclave = { path = "../../../test_enclave" }

[build-dependencies]
bindgen = "0.60.1"
cargo-emit = "0.2.1"

mc-sgx-core-build = { path = "../../../core/build" }
